// 'use server'
'use server';

/**
 * @fileOverview This file defines a Genkit flow for generating assessment ideas using the Gemini API.
 *
 * - getGeminiAssessmentIdeas: An async function that takes input text and course context and returns assessment ideas.
 * - GetGeminiAssessmentIdeasInput: The input type for the getGeminiAssessmentIdeas function.
 * - GetGeminiAssessmentIdeasOutput: The return type for the getGeminiAssessmentIdeas function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GetGeminiAssessmentIdeasInputSchema = z.object({
  inputText: z.string().describe('The input text containing the topic, learning objective, or keywords related to the course content.'),
  courseContext: z.string().describe('Contextual information about the course for which assessment ideas are needed.'),
});
export type GetGeminiAssessmentIdeasInput = z.infer<typeof GetGeminiAssessmentIdeasInputSchema>;

const GetGeminiAssessmentIdeasOutputSchema = z.object({
  assessmentIdeas: z.string().describe('A list of assessment ideas generated by the Gemini API.'),
});
export type GetGeminiAssessmentIdeasOutput = z.infer<typeof GetGeminiAssessmentIdeasOutputSchema>;

export async function getGeminiAssessmentIdeas(input: GetGeminiAssessmentIdeasInput): Promise<GetGeminiAssessmentIdeasOutput> {
  return getGeminiAssessmentIdeasFlow(input);
}

const getGeminiAssessmentIdeasPrompt = ai.definePrompt({
  name: 'getGeminiAssessmentIdeasPrompt',
  input: {schema: GetGeminiAssessmentIdeasInputSchema},
  output: {schema: GetGeminiAssessmentIdeasOutputSchema},
  prompt: `You are an AI assistant designed to help teachers generate assessment ideas for their courses.

  Given the following input text and course context, generate a list of assessment ideas that the teacher can use to assess student learning.

  Input Text: {{{inputText}}}
  Course Context: {{{courseContext}}}

  Assessment Ideas:`,
});

const getGeminiAssessmentIdeasFlow = ai.defineFlow(
  {
    name: 'getGeminiAssessmentIdeasFlow',
    inputSchema: GetGeminiAssessmentIdeasInputSchema,
    outputSchema: GetGeminiAssessmentIdeasOutputSchema,
  },
  async input => {
    const {output} = await getGeminiAssessmentIdeasPrompt(input);
    return output!;
  }
);
