// In-memory store for users for API route demonstration
// This data will reset when the server restarts.

import type { UserProfile } from '@/stores/appStore';

export let usersStore: UserProfile[] = [
  { user_id: 'admin', username: 'admin', email: 'admin@cotbe.edu', role: 'Admin', first_name: 'Portal', last_name: 'Admin', is_active: true, date_joined: new Date(Date.now() - 1000 * 24 * 60 * 60 * 1000).toISOString(), last_login: new Date().toISOString(), job_title: "System Administrator", phone_number: "0900000000", password_hash: "hashed_admin" },
  { user_id: 'stud1', username: 'stud1', email: 's1@cotbe.edu', role: 'Student', first_name: 'Abebe', last_name: 'Bekele', is_active: true, date_joined: new Date(Date.now() - 200 * 24 * 60 * 60 * 1000).toISOString(), last_login: new Date().toISOString(), department_id: 'dept-1', department_name: "Computer Science", enrollment_date: "2022-09-01", date_of_birth: "2003-05-10", address: "Arat Kilo, Addis Ababa", phone_number: "0911111111", password_hash: "hashed_stud1" },
  { user_id: 'teacher-1', username: 'teacher.one', email: 't1@cotbe.edu', role: 'Teacher', first_name: 'Chaltu', last_name: 'Lemma', is_active: true, date_joined: new Date(Date.now() - 500 * 24 * 60 * 60 * 1000).toISOString(), last_login: new Date().toISOString(), department_id: 'dept-2', department_name: "Electrical Engineering", office_location: "Block C, Room 203", phone_number: "0922222222", password_hash: "hashed_teacher.one" },
  { user_id: 'staff1', username: 'staff.one', email: 'staff1@cotbe.edu', role: 'Staff Head', first_name: 'Kebede', last_name: 'Tadesse', is_active: true, date_joined: new Date(Date.now() - 1000 * 24 * 60 * 60 * 1000).toISOString(), last_login: new Date().toISOString(), job_title: "Registry Head", phone_number: "0933221100", password_hash: "hashed_staff.one" },
  { user_id: 'stud2', username: 'stud2', email: 's2@cotbe.edu', role: 'Student', first_name: 'Hana', last_name: 'Girma', is_active: true, date_joined: new Date(Date.now() - 150 * 24 * 60 * 60 * 1000).toISOString(), last_login: new Date().toISOString(), department_id: 'dept-1', department_name: "Computer Science", enrollment_date: "2023-03-15", date_of_birth: "2004-01-20", address: "Bole, Addis Ababa", phone_number: "0933333333", password_hash: "hashed_stud2" },
  { user_id: 'stud3', username: 'stud3', email: 's3@cotbe.edu', role: 'Student', first_name: 'Yonas', last_name: 'Ayele', is_active: false, date_joined: new Date(Date.now() - 100 * 24 * 60 * 60 * 1000).toISOString(), last_login: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(), department_id: 'dept-3', department_name: "Civil Engineering", enrollment_date: "2023-09-01", date_of_birth: "2002-11-05", address: "Piassa, Addis Ababa", phone_number: "0944444444", password_hash: "hashed_stud3" },
  { user_id: 'teacher-2', username: 'teacher.two', email: 't2@cotbe.edu', role: 'Teacher', first_name: 'Solomon', last_name: 'Gizaw', is_active: true, date_joined: new Date(Date.now() - 400 * 24 * 60 * 60 * 1000).toISOString(), last_login: new Date().toISOString(), department_id: 'dept-1', department_name: "Computer Science", office_location: "Block A, Room 105", phone_number: "0912987654", password_hash: "hashed_teacher.two" },
];
